apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-python
spec:
  template:
    metadata:
      name: hello-python-v1
    spec:
      containers:
        - image: quay.io/jkeam/hello-python
          env:
            - name: TARGET
              value: "Python"
