apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: serverless-workshop-ml
spec:
  generateBucketName: 'serverless-workshop-ml'
  storageClassName: openshift-storage.noobaa.io
