apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workshop-objectbucket-viewers
subjects:
- kind: Group
  name: workshop
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: objectbuckets.objectbucket.io-v1alpha1-view
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-view
rules:
- apiGroups: ["operators.coreos.com"]
  resources: ["operators"]
  verbs: ["list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kafka
  name: kafka-view
rules:
- apiGroups: ["kafka.strimzi.io"]
  resources: ["kafkas"]
  verbs: ["list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: knative-eventing
  name: knative-eventing-view
rules:
- apiGroups: ["", "kafka.strimzi.io", "operator.knative.dev"]
  resources: ["pods", "knativeeventings"]
  verbs: ["list", "get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: knative-serving
  name: knative-serving-view
rules:
- apiGroups: ["", "kafka.strimzi.io", "operator.knative.dev"]
  resources: ["pods", "knativeservings"]
  verbs: ["list", "get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workshop-operator-viewers
subjects:
- kind: Group
  name: workshop
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: operator-view
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workshop-kafka-viewers
  namespace: kafka
subjects:
- kind: Group
  name: workshop
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: kafka-view
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workshop-knative-eventing-viewers
  namespace: knative-eventing
subjects:
- kind: Group
  name: workshop
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: knative-eventing-view
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workshop-knative-serving-viewers
  namespace: knative-serving
subjects:
- kind: Group
  name: workshop
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: knative-serving-view
  apiGroup: rbac.authorization.k8s.io
