apiVersion: v1
kind: ConfigMap
metadata:
  name: config-default-kafka-channel
  namespace: knative-eventing
data:
  default-ch-config: |
    clusterDefault:
      kafka:
        apiVersion: messaging.knative.dev/v1alpha1
        kind: KafkaChannel
        spec:
          numPartitions: 1
          replicationFactor: 1
