apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: mykafka-source
spec:
  consumerGroup: knative-group-USER_NUMBER
  bootstrapServers:
    - my-cluster-kafka-bootstrap.kafka:9092
  topics:
    - my-topic-USER_NUMBER
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: eventinghello
